apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}
type: Opaque
data:
  AZP_TOKEN: {{ .Values.AZP_TOKEN }} 
  AZP_POOL: {{ .Values.AZP_POOL }} 